name: bili-gist-python
description: Update a pinned gist to show your Bilibili stats and your latest videos.
inputs:
  BILI_SESSDATA:
    description: Your bilibili sessdata
    required: true
  BILI_UID:
    description: Bilibili uid
    required: true
  GIST_ID:
    description: Your gistid
    required: true
  GH_TOKEN:
    description: Your gh_token with gist permission
    required: true
runs:
  using: composite
  steps:
  - name: setup python
    uses: actions/setup-python@v5
    with:
      python-version: 3.8
      cache: 'pip'
      cache-dependency-path: '**/requirements.txt'
  - name: Install requirement
    run: pip install -r $GITHUB_ACTION_PATH/requirements.txt
    shell: bash
  - name: Update gist
    run: python $GITHUB_ACTION_PATH/gist.py
    shell: bash
