name: Update gist
on:
  workflow_dispatch:
  push:
    branches: master
  schedule:
    - cron: "0 */24 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
          cache: 'pip'
          cache-dependency-path: '**/requirements.txt'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Update gist
        run: python gist.py
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 181a99b82ae47d3a6fccbd126f9d93ef
          BILI_SESSDATA: ${{ secrets.BILI_SESSDATA }}
          BILI_UID: '282873551'
      - name: output logs
        run: cat log.log >>$GITHUB_STEP_SUMMARY
